### ISSUE TITLE
关于播放错误的问题

### ISSUE THREAD

**Issue by hushuoking** [Louie-v/MyMusicBox#7]
下载mp3没有问题。但是无发播放是什么原因能麻烦问一下您么
Exception in thread player:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/box/play.py", line 117, in playPopen
    self.popenHandler = subprocess.Popen(["mpg123", "-R"],stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Louie-v** [comment]
OSError: [Errno 2] No such file or directory
这是没有找到可播放的文件，请查看控制台中的Music ID对应的文件是否存在？

**Comment by Louie-v** [comment]
对了，上次合并了分支，最新播放已使用mpg123来播放音乐，请尝试在树莓派上安装mpg123后再试
尝试此命令  `sudo apt-get  install mpg123`
忘了更新ReadME
